### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by gogobebe2**

### CODE REVIEW

**Comment by gogobebe2** [comment]
jk

**Comment by Oper8or** [comment]
are you even the original coder?

**Comment by gogobebe2** [comment]
Naa, I'm just messing about with it. I don't code in C++ and it's always fun to learn a new language. I actually though this was my own fork of yours and I clicked create pull request from this account for my other account. That's why I replied straight away with "jk" because I realised I made a retarded mistake xD

**Comment by Oper8or** [comment]
lol

**Comment by gogobebe2** [comment]
Nice shit though :+1:. :sob: Bye xD

**Pull request closed without merging**
